{% set name = "ligo-segments" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e072a844713c5b02efdcaf5bfe4c3a8cd9ef225b08cfd3202a4e185e0f71f5dc

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  ignore_run_exports:
    - m2w64-gcc-libs  # [win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}  # [not win]
    - {{ compiler('m2w64_c') }}  # [win]
  host:
    - libpython  # [win]
    - pip
    - python
    - setuptools
  run:
    - python
    - six

test:
  source_files:
    - test/*.py
  requires:
    - pip
    # only run lal test on established platforms
    - python-lal  # [x86_64 and not win]
  commands:
    # check requirements
    - python -m pip check
    # run tests
    - python test/segments_verify.py
    - python test/segments_utils_verify.py  # [x86_64 and not win]

about:
  home: https://git.ligo.org/lscsoft/ligo-segments/
  dev_url: https://git.ligo.org/lscsoft/ligo-segments.git
  doc_url: https://lscsoft.docs.ligo.org/ligo-segments/
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Representations of semi-open intervals
  description: |
    This module defines the segment and segmentlist objects, as well as the
    infinity object used to define semi-infinite and infinite segments.

extra:
  recipe-maintainers:
    - duncanmmacleod
