travis:
  secure:
    BINSTAR_TOKEN: xB4J9obHrPSoVo2JxIc4C2Z/CjfVK25ABtamKQNu30OBcXzEziR+nvm5EkhkBr09SVkAQxsD4QxMrXV4B/9edjqza1/KAl67SC+I+frfG8I1D3CkvOwv3usivrqXZRzl8/NkNEwKXNoIwP5Sz4373y5VJrxP0bOPML5J9gj+zTmuh0QoSjeufL1VJZgoctE2efrbcx/Z09sql2LQLoGfEPPqwz8JnilV6mQoj8M+oO+0o4qOLrV1BunyQNxeeEI7E7wUC7voyFOOXd1qUK5sda0whD0rh4GdJZLUc3jwKp7USPg+f7TrFh/P3TY3/faSV4Dyah89YEIePFDKqRGsbIW39N+XngkDg3a95SzfumeuxsLam0znDNYAtPGt9RAremMqnL8yiWMwJFbnUXGsDsYon+wPTLHWtJaBB/gLLPERhhKHAi0BeTcW0xN+9Avs+Vmnj9Pfl0aW12LprHZTIW0DcoN1zqtCUewibUIx1HpiokmTj+fSfQScJEtejIBt13b0/gXkxzuv3+wTVoQPakrdmjGjnpYB2DGueNnohbRiayOMh6ci+affDmnGKIsfMVoWRks+250QfCroy4velfcujSK7lx6+kOXsZgcxyF3DnNDFGCep46wvGsqaiJoMn9DO5Uw+aBc/5KY4PifIyxwEol8f82qQk0Kn3HbKkr4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
