travis:
  secure:
    BINSTAR_TOKEN: ibIHRN6RvH3+0fcCu4TQKST1R2AtLR0MuIoJmuBGYiu8zQas++vJ8PZ0Mu3W7y7/4nHCXHvLc0Q4eovluOsBGDvlxXApYDES6R9PpkSk8u4aq05GHIs2sQ17mbbeSOoQqzAxJ24zWbr8oB3n5umZM8qctd5+KmvP++93ZTCOtAGdw5dEXtMFiA1F5qX1A3opSVqz8GDYykvEHC77JZ3toey6L4m0T8lwILwVdeFhWXTEmDaQAa0ohqH68Ib5cfqiseaLBez4l6aFHjNrIq6qRCpA9pfFWrKTFLrZq6wWTGHbhH3o5t7b132kUze7PBUJ8Ilxf+7FrXp7EhMMkdXJook7RXBzosSmaECiUe4rPRhCs8QpQeTtW/XvaZAFkrlEFUKRxtGYRV5MWXNJybzFiSJ639fIBr01nvCiwNVm4Hj1QaWZ1nYNFM4hiKzffL7IJC4Ta7C8KcHSaaO6kaxQOn8AgBfHl9pOnki21Xgckk31pY48KQCpZWyMFyeYUAIPoHw2TGAIb0Z6F//Vs8RiNNtvtfTWOTD/LnIxzgCijKchj/KcnN/f+MiOAis6fBYr3jcKT8fk65ODt2YCr9BZusZUM5ML77CXMLFowgHT6jXpALw020DHBiYtqouL2xbDhgHhJUPK++JAJj3Iarup7Sxdm7vOT7vhSMWxMQhe9gc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
